services:
  web:
    build: .
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./html:/usr/share/nginx/html
    depends_on:
      - app

  app:
    build: ./app
    container_name: app-container
    volumes:
      - ./data:/data
      - ./tests:/app/tests
    environment:
      - DB_HOST=db
      - DB_NAME=testdb
      - DB_USER=user
      - DB_PASS=password
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1517413796635738163/enUmviWs57nqepOgYpEZz2OxE61EaVaIicPi8Fb2kUIeeQLKXtqs5WzK-vcM4dxWuI3t
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db-container
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
