server {
    listen 80;
    server_name xn--r9j5b5b.jp;

    return 301 https://$host$request_uri;
}

server {
    listen 80 default_server;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /status/ {
        alias /usr/share/nginx/html/status/;
        index index.html;
    }

    location /read {
        proxy_pass http://app:5000/read;
    }

    location /save {
        proxy_pass http://app:5000/save;
    }

    location /init {
        proxy_pass http://app:5000/init;
    }

    location /health {
        proxy_pass http://app:5000/health;
    }

    location /api/cpu {
        proxy_pass http://app:5000/api/cpu;
    }

}

server {
    listen 443 ssl;
    server_name xn--r9j5b5b.jp;

    ssl_certificate /etc/letsencrypt/live/xn--r9j5b5b.jp/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xn--r9j5b5b.jp/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /status/ {
        alias /usr/share/nginx/html/status/;
        index index.html;
    }

    location /read {
        proxy_pass http://app:5000/read;
    }

    location /save {
        proxy_pass http://app:5000/save;
    }

    location /init {
        proxy_pass http://app:5000/init;
    }

    location /health {
        proxy_pass http://app:5000/health;
    }

    location /api/cpu {
        proxy_pass http://app:5000/api/cpu;
    }

}
