name: Deploy to AWS

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build containers for test
        run: docker compose up -d --build app

      - name: Run tests
        run: docker compose exec -T app sh -c "PYTHONPATH=/app pytest"

      - name: Stop test containers
        if: always()
        run: docker compose down

      - name: SSH to AWS and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 32.236.14.51
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/docker-status
            ./deploy.sh
